### PR TITLE
Fix Codestyle for https://github.com/joomla/joomla-cms/pull/6728

### PR DESCRIPTION
**Pull request by zero-24**
@orware this fix some codestyle for https://github.com/joomla/joomla-cms/pull/6728

### CODE REVIEW

**Comment by orware** [comment]
Hi @zero-24 I'm just curious where all of these additional codestyle suggestions came from?

Some of them look fine, but most of what I'm seeing is adjusting the alignments of variables to their assigned values. So instead of just being:

```
$someVar = 'someValue';
$someLongerVar = 'someOtherValue';
```

I'm seeing a lot of:
```
$someVar       = 'someValue';
$someLongerVar = 'someOtherValue';
```

And I'm just curious to know if these rules are being applied to everything in the codebase?

**Comment by zero-24** [comment]
>Hi @zero-24 I'm just curious where all of these additional codestyle suggestions came from?

It makes it much easier to read the code. :smile: But if you do not agree with it close here and let the code untoched.

**Comment by orware** [comment]
Did you end having to go through the file manually to make the changes or do you have something automated on your end that helped to make them?

I don't necessarily disagree with the changes, but it would definitely make it easier for me to say yes if I knew it was a more official code style that the project used for everything.

For now I'll go ahead and leave it as-is (though I really do appreciate you taking the time to create the PR...and I really do hope you'll continue with testing the overall patch out on your end :-).

If I get some more info on the code style changes being highly recommended I'll definitely come back here and merge this in (I think part of the reason for the hesitation right now is I remember that style for PHP variables used to be used back in the earlier Joomla days but I think it stopped being used a few years back so I was a little surprised to see it in your PR).

**Comment by zero-24** [comment]
try
>There should be space before and exactly one space after the equals sign. Tab alignment over multiple lines is permitted.

Function Calls -> http://joomla.github.io/coding-standards/?coding-standards/chapters/php.md

and
https://github.com/joomla/joomla-cms/pull/5761/files

else feel free to close here.

**Comment by zero-24** [comment]
maybe this: https://github.com/joomla-extensions/install-from-web-server/pull/13/files#diff-e90735bad746b1e6e408e4c2a9d552a4R10 and other can also help :smile:

**Comment by zero-24** [comment]
Closing in lack of interest.

**Pull request closed without merging**
